### ISSUE TITLE
Todo Feature

### ISSUE THREAD

**Issue by bpotmalnik** [mszakacz/better_organizer#2]
We need to add feature to the app which will
- [ ] list todo's 
- [ ] create todo list item
- [ ] edit todo list item 
- [ ] delete todo list item
- [ ] show history of completed todo's
